fix(MT-1792): adding support for laravel 9.2
LiveIntent/sdk-php pull request #7
Opened 2022-05-12 06:21 UTC by ashishkumarqait

2022-05-17 19:35 UTC, chintan-liveintent commented on composer.json
> -        "spatie/phpunit-watcher": "^1.23",
Just as a heads up, I've removed this dependency.

2022-05-18 13:44 UTC, rrmanalo623 commented on tests/Services/AdSlotServiceTest.php
> -            'sizes' => [
Please do not remove this from the test. Or if you want to remove it that's fine, but we need to make sure we can support sizes as it is in LSD.

2022-05-18 13:47 UTC, rrmanalo623 commented on src/Services/Concerns/MocksRequests.php
> -
After removing this - are you sure we can still support sizes as is with LSD?? This was added specifically to support sizes and other patterns like it that's not a simple data type.

2022-05-18 13:47 UTC, rrmanalo623 requested changes
Please see comments in PR.

2022-05-18 13:58 UTC, ashishkumarqait commented on src/Services/Concerns/MocksRequests.php
> -
with this new version this was the reason of most test errors, it was causing request body to be `empty`, will check what was going there earlier

2022-05-18 13:59 UTC, ashishkumarqait commented on tests/Services/AdSlotServiceTest.php
> -            'sizes' => [
I tried but it failed, may be another comment has to do something with this

2022-05-18 14:24 UTC, ashishkumarqait commented on src/Services/Concerns/MocksRequests.php
> -
Confirmed: this is working for sizes if I turn off mocking, so that means there may be an issue with stub data, looking into it.

2022-05-18 18:09 UTC, tam5 approved these changes
LGTM

2022-05-19 02:40 UTC, ashishkumarqait commented on tests/Services/AdSlotServiceTest.php
> -            'sizes' => [
hey @rrmanalo623 tried it but not working, looks like this is going to take some time, can we create a seperate ticket to tackle this test, and unblock the release for gam work?

2022-05-20 00:25 UTC, merged

2022-05-20 00:32 UTC, tam5 commented
this broke a bunch of tests, restoring